# Generated by Django 4.0.5 on 2023-03-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rifle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('place_of_origin', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
